### ISSUE TITLE
Just Getting notification to update

### ISSUE THREAD

**Issue by thevectorbox** [taohsu/skeletongenerator#1]
It's giving constant update notification of 1.0.1 somehow even after updating, on click of update, nothing happens!

**Comment by custa1200** [comment]
Would be good @taohsu  if you could publish an update that fixes this.

**Comment by GundlachApp** [comment]
Would be rather usefull if you could fix the notification. OCD won't allow me to use your plugin if I have to see the red dot all the time 👯

**Comment by taohsu** [comment]
Sorry for the late response 🥲 The notification issue should be fixed now!
Please just retry to update to v1.0.1. Let me know if the problem remains. 
Thanks for using this plug-in!

**Comment by GundlachApp** [comment]
Thanks!

The errormessage is stll the same, but if you ignore it, it does its work and notification disappears :)
